// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzRoJVGEStzAd6_Q29z8oxinABCFGiWg',
    appId: '1:451170099814:web:2d2f16a91026c5297d43a7',
    messagingSenderId: '451170099814',
    projectId: 'fir-chatapp-668f0',
    authDomain: 'fir-chatapp-668f0.firebaseapp.com',
    storageBucket: 'fir-chatapp-668f0.appspot.com',
    measurementId: 'G-Y3DCSJQDT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC56347rZOb_lLuOMi6NhZBfQwJXXRWwVk',
    appId: '1:451170099814:android:42f35adc9ffd46037d43a7',
    messagingSenderId: '451170099814',
    projectId: 'fir-chatapp-668f0',
    storageBucket: 'fir-chatapp-668f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3csyAU3959S7eQCKtUTiyfhaDAb3QrDA',
    appId: '1:451170099814:ios:ce2cb5106e6c4d297d43a7',
    messagingSenderId: '451170099814',
    projectId: 'fir-chatapp-668f0',
    storageBucket: 'fir-chatapp-668f0.appspot.com',
    iosClientId: '451170099814-fn1u24j0r13jcjv7hf4su6ef5je70peu.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3csyAU3959S7eQCKtUTiyfhaDAb3QrDA',
    appId: '1:451170099814:ios:ce2cb5106e6c4d297d43a7',
    messagingSenderId: '451170099814',
    projectId: 'fir-chatapp-668f0',
    storageBucket: 'fir-chatapp-668f0.appspot.com',
    iosClientId: '451170099814-fn1u24j0r13jcjv7hf4su6ef5je70peu.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );
}
